# app config #
host: 0.0.0.0
port: 8080
cache_path: tmp

# use this secret to update your posts
update_endpoint: /update
update_secret: 123456

# configure object storage to automatically obtain article updates
storage:
  src: _blog/src/post
  dst: _blog/dst/post
  auto_pull: true
  type: COS
  cos:
    appid:
    bucket:
    region:
    secret_id:
    secret_key:
    save_path:

# website template directory
template: templates/default

# site config #
site:
  # basic info
  info:
    logo: /assets/img/logo.png
    motto:
      - I hope I can make it out of here.
      - I hope that I can still feel the sun on my face, and hear the sound of the rain.
      - I hope that I can walk with my head held high again, free, and one day be able to say,
      - I’m not just living,
      - I’m truly alive.
      - <br>
      - —— Andy Dufresne
    title: Molly Blog
    author: yvling
    language: en
    copyright: Copyright © 2024 Powered by <a href="https://github.com/yv1ing/MollyBlog">MollyBlog</a>

  # menu config
  menu:
    items:
      - name: Home
        icon: fa-solid fa-house
        url: /
      - name: Archive
        icon: fa-solid fa-box-archive
        url: /archive
      - name: About
        icon: fa-solid fa-circle-info
        url: /about

  # post config
  post:
    toc_title: Content

    # title and number of post displayed per page
    recent_post:
      title: Recent Posts
      number: 10
    archive:
      title: Archive
      number: 10
    search:
      title: Search
      number: 10
    category:
      title: Category
      number: 10
    tag:
      title: Tag
      number: 10

  # about config
  about:
    title: About me
    src: _blog/src/about
    dst: _blog/dst/about
    filename: index